services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloaks
      POSTGRES_USER: keycloaks
      POSTGRES_PASSWORD: keycloaks
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloaks
      DB_USER: keycloaks
      DB_PASSWORD: keycloaks
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --http-port=8080
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    networks:
      - keycloak-network
      - app-network

  public-side:
    build: ./publicSide
    container_name: public-side
    ports:
      - "3000:3000"
    networks:
      - app-network

  admin-panel:
    build: ./adminPanel
    container_name: admin-panel
    ports:
      - "4000:4000"
    networks:
      - app-network

  personal-account:
    build: ./personal-account
    container_name: personal-account
    ports:
      - "8000:8000"
    networks:
      - app-network

  testing:
    build: ./testing
    container_name: testing
    ports:
      - "8085:8085"
    networks:
      - app-network

networks:
  networks:
  keycloak-network: # Изолированная сеть для Keycloak и его БД
    driver: bridge
    internal: true
  app-network: # Общая сеть для приложений, общей БД и nginx
    driver: bridge

volumes:
  keycloak_data:
    driver: local
